[package]
name = "rust-cookbook"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
clap = "4.4.8"
ansi_term = "0.12.1"
flate2 = "1.0.28"
tar = "0.4.40"
